services:
  db:
    image: postgres:17
    container_name: ${database_name:-reflecto_db}
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=db
    volumes:
      - /var/lib/postgresql/17/main/:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file: 
      - ./backend/.env
    container_name: ${backend_name:-reflecto_backend}
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./backend:/app
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/lib/data:/usr/src/backend/data
      - /var/logs/reflecto_backend:/var/logs/reflecto_backend
    depends_on:
      - db
  frontend:
    build: ./frontend
    env_file:
        - ./frontend/.env
    container_name: ${frontend_name:-reflecto_frontend}
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - backend
